- README.md
- build.gradle
- src/main/java/com/amazon/opendistroforelasticsearch/commons/ConfigConstants.java
- src/main/java/com/amazon/opendistroforelasticsearch/commons/InjectSecurity.java
- src/main/java/com/amazon/opendistroforelasticsearch/commons/authuser/AuthUserRequestBuilder.java
- src/main/java/com/amazon/opendistroforelasticsearch/commons/authuser/User.java
- src/main/java/com/amazon/opendistroforelasticsearch/commons/rest/SecureRestClientBuilder.java
- src/main/java/com/amazon/opendistroforelasticsearch/commons/rest/TrustStore.java
- src/test/java/com/amazon/opendistroforelasticsearch/commons/InjectSecurityTest.java
- src/test/java/com/amazon/opendistroforelasticsearch/commons/authuser/UserTest.java
- src/test/java/com/amazon/opendistroforelasticsearch/commons/rest/IntegrationTests.java
- src/test/java/com/amazon/opendistroforelasticsearch/commons/rest/SecureRestClientBuilderTest.java
- src/test/java/com/amazon/opendistroforelasticsearch/commons/rest/TrustStoreTest.java
Signed-off-by: Vacha Shah <vachshah@amazon.com>
This PR updates the namespaces in `common-utils` from OpenDistro to OpenSearch.
Part 1 of #19.
> Rename namespaces from OpenDistro to OpenSearch

- README.md
- build.gradle
- src/main/java/org/opensearch/commons/InjectSecurity.java
Signed-off-by: Vacha Shah <vachshah@amazon.com>
This PR updates the remaining identifiers from OpenDistro to OpenSearch.
Part 3 of #19 
> Rename remaining identifiers to OpenSearch

- build.gradle
Removing Kotlin Runtime library bundled into library
Also Currently plugins are using kotlin version 1.4 so using the same
> Removing Kotlin Runtime library bundled into library

- .github/workflows/ci.yml
- build.gradle
Signed-off-by: bowenlan-amzn <bowenlan23@gmail.com>
Bump to version 1.0.0.0 for OS 1.0 GA release
> Bump to version 1.0.0.0

- release-notes/opensearch-common-utils.release-notes-1.0.0.0.md
> Update Release Notes for GA

- src/main/kotlin/org/opensearch/commons/notifications/model/HttpMethodType.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/Webhook.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/WebhookTests.kt
Signed-off-by: Zhongnan Su <szhongna@amazon.com>
- Add `method` field in webhook data model to accept `PUT`, `POST`, `PATCH` 
data-model part of https://github.com/opensearch-project/notifications/issues/219
> [Notification] add method type in CustomWebhook data model

- src/main/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterface.kt
- src/test/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterfaceTests.kt
- src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Type cast error occurred when entering `ActionResponse.onResponse()`. The reason is due to different class loaders across plugins that explained in details here: https://github.com/opensearch-project/notifications/pull/223. To solve the problem in similar way, wrap the listener by a new one with only difference on generic type (which is abstract `ActionResponse` rather than concrete `XXXNotificationResponse` to delay the casting operation after recreating response object by class loaded by current plugin class loader.
The main wrapper logic is patched from this https://github.com/opensearch-project/common-utils/pull/38. This PR is focused on adding missing UT to cover all notification APIs touched.
https://github.com/opensearch-project/common-utils/issues/37
By submitting this pull …
> Fix class loader issue for notifications response

- release-notes/opensearch-common-utils.release-notes-1.0.0.0.md
- src/main/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/HttpMethodType.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/Webhook.kt
- src/test/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/WebhookTests.kt
- src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
[Releasing Instructions](https://github.com/opensearch-project/.github/blob/main/RELEASING.md)
https://github.com/opensearch-project/common-utils/issues/33
> Merge changes in the main branch to the 1.x branch.

- src/main/kotlin/org/opensearch/commons/utils/ValidationHelpers.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/ChimeTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/SlackTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/WebhookTests.kt
remove https only restrictions on webhook url protocols
notificatuion side change is made in this PR https://github.com/opensearch-project/notifications/pull/248
https://github.com/opensearch-project/notifications/issues/232
> [Notification] remove https only restrictions on webhook url protocols

- .github/workflows/ci.yml
- build.gradle
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>
Bumping up common-utils to build with OpenSearch `main` which is 1.1.0.
As with the branching and release strategy for the project https://github.com/opensearch-project/.github/issues/13
Here is how it should look like:
1. Plugin/library `main` builds out of OpenSearch `main`. 
2. Plugin/library `1.x` builds out of OpenSearch `1.x`.
3. Plugin/library `1.0` builds out of OpenSearch `1.0`.
This allows us to fail fast and get ready for release.
As part of adding backwards compatibility test framework, we are developing tests as an example in Anomaly Detection which needs common-utils. 
Ref: https://github.com/opensearch-project/OpenSearch/issues/1002
Meta issue: https://github.com/opensearch-project/opensearch-build/issues/90
#46 …
> Bumping common-utils to build with OpenSearch(main) 1.1.0

- src/main/java/org/opensearch/commons/InjectSecurity.java
- src/test/java/org/opensearch/commons/InjectSecurityTest.java
Signed-off-by: Ravi Thaluru <ravi1092@gmail.com>
Adding an utility method to allow callers to set custom thread context property and value
N/A
> Adding an utility method that allows consumers to set custom thread context property in InjectSecurity class

- src/main/kotlin/org/opensearch/commons/notifications/NotificationConstants.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/ConfigType.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/EventStatus.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/SNS.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/config/ConfigDataProperties.kt
- src/main/kotlin/org/opensearch/commons/utils/ValidationHelpers.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/SNSTests.kt
Add SNS model required to support SNS channels in Notifications plugin.
Add unit tests.
- https://github.com/opensearch-project/notifications/issues/150
- https://github.com/opensearch-project/notifications/issues/151
- https://github.com/opensearch-project/notifications/issues/156
- https://github.com/opensearch-project/notifications/issues/157
> Add Notifications SNS model

- .github/workflows/ci.yml
- build.gradle
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>
Bumping up common-utils to build with OpenSearch `main` which is 1.1.0.
As with the branching and release strategy for the project https://github.com/opensearch-project/.github/issues/13
Here is how it should look like:
1. Plugin/library `main` builds out of OpenSearch `main`. 
2. Plugin/library `1.x` builds out of OpenSearch `1.x`.
3. Plugin/library `1.0` builds out of OpenSearch `1.0`.
This allows us to fail fast and get ready for release.
As part of adding backwards compatibility test framework, we are developing tests as an example in Anomaly Detection which needs common-utils. 
Ref: https://github.com/opensearch-project/OpenSearch/issues/1002
Meta issue: https://github.com/opensearch-project/opensearch-build/issues/90
#46 …
> [1.x] Bumping common-utils to build with OpenSearch(1.x) 1.1.0

- src/main/java/org/opensearch/commons/destination/message/LegacyBaseMessage.java
- src/main/java/org/opensearch/commons/destination/message/LegacyChimeMessage.java
- src/main/java/org/opensearch/commons/destination/message/LegacyCustomWebhookMessage.java
- src/main/java/org/opensearch/commons/destination/message/LegacyDestinationType.java
- src/main/java/org/opensearch/commons/destination/message/LegacySlackMessage.java
- src/main/java/org/opensearch/commons/destination/response/LegacyBaseResponse.java
- src/main/java/org/opensearch/commons/destination/response/LegacyDestinationResponse.java
- src/main/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/LegacyPublishNotificationRequest.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/LegacyPublishNotificationResponse.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/NotificationsActions.kt
- src/test/java/org/opensearch/commons/destination/message/LegacyChimeMessageTest.java
- src/test/java/org/opensearch/commons/destination/message/LegacyCustomWebhookMessageTest.java
- src/test/java/org/opensearch/commons/destination/message/LegacySlackMessageTest.java
- src/test/java/org/opensearch/commons/destination/response/LegacyDestinationResponseTest.java
- src/test/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/LegacyPublishNotificationRequestTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/LegacyPublishNotificationResponseTests.kt
…or publishing legacy notifications, and method for executing transport action
Signed-off-by: Drew Baugher 46505179+dbbaughe@users.noreply.github.com
Adds required legacy messages, request/response classes, and methods for ISM to publish a notification through the notification plugin with the old embedded types without having to create a channel first.
opensearch-project/notifications#253
https://github.com/opensearch-project/common-utils/issues/44
> Adds legacy chime, slack, custom webhook messages, request/response f

- .github/workflows/ci.yml
- build.gradle
Signed-off-by: Vacha <vachshah@amazon.com>
Consuming OpenSearch 1.1 version snapshot instead of 1.1. This is required since AD consumes the 1.1 snapshot artifact (details in PR https://github.com/opensearch-project/anomaly-detection/pull/175).
As part of closed issue #46.
> Using 1.1 snapshot version for OpenSearch

- .github/workflows/ci.yml
- build.gradle
Builds snapshot by default and always matches OpenSearch version.
Closes #56.
> Fix and build snapshot build by default

- src/main/kotlin/org/opensearch/commons/notifications/model/SesAccount.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/SesAccountTests.kt
BugFix: Allow null values for role_arn in json parsing
Allow null values for role_arn in json parsing
> BugFix: Allow null values for role_arn in json parsing

- .github/workflows/ci.yml
- build.gradle
This change adds commits related to snapshot build of Common Utils on 1.1
#64
#65
> Add Commits related to Snapshot build of Common Utils on 1.1

- build.gradle
This fixes https://github.com/opensearch-project/opensearch-build/pull/430/checks?check_run_id=3569950574 by cherry-picking cc02f237de3ef45c3f7dc0bf526556d09bbaba97 from #58. The JAR version needs to be 1.1.0.0-SNAPSHOT when building a snapshot, and 1.1.0.0 otherwise, which is handled in property resolution.
> Correct hard-coded version.

- src/main/java/org/opensearch/commons/InjectSecurity.java
- src/test/java/org/opensearch/commons/InjectSecurityTest.java
Adding an utility method that allows consumers to set custom thread context property in InjectSecurity class (#47)
Signed-off-by: Ravi Thaluru <ravi1092@gmail.com>
> Backport Index Management security integration related commit to 1.1

- .github/workflows/ci.yml
- src/main/kotlin/org/opensearch/commons/notifications/NotificationConstants.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/GetFeatureChannelListRequest.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/NotificationConfigInfo.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/NotificationEventInfo.kt
- src/test/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/GetNotificationConfigResponseTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/GetNotificationEventResponseTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/NotificationConfigInfoTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/NotificationConfigSearchResultsTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/NotificationEventInfoTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/NotificationEventSearchResultTests.kt
> Removed tenant information from the models

- src/main/kotlin/org/opensearch/commons/notifications/NotificationConstants.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/GetPluginFeaturesResponse.kt
- src/test/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/GetPluginFeaturesResponseTests.kt
Updated the plugin feature response with allowed config features
[Tests]
Updated the unit tests
> Updated the plugin feature response with allowed config features

- .github/workflows/ci.yml
- build.gradle
Signed-off-by: Clay Downs <downsrob@amazon.com>
Updates common utils version to 1.2. Changes the gradle build file, as well as the github test and build workflow.
opensearch-project/opensearch-build#663
> Updates common-utils version to 1.2

- build.gradle
- scripts/build.sh
Signed-off-by: Marc Handalian <handalm@amazon.com>
This change adds a new task to publish to a local staging repo that includes checksums.  Also update build.sh to use this new task and copy the contents of the staging repo to the output directory.
The maven publish plugin will not include these cksums when publishing to maven local but will when published to a separate folder.
```
./scripts/build.sh -v 1.2.0-SNAPSHOT  
```
Result:
```
~/workspace/common-utils (maven)$ find artifacts/maven/org/opensearch/common-utils/
artifacts/maven/org/opensearch/common-utils/
artifacts/maven/org/opensearch/common-utils//maven-metadata.xml.sha256
artifacts/maven/org/opensearch/common-utils//maven-metadata.xml
artifacts/maven/org/opensearch/common-utils//maven-metadata.xml.sha512 …
```
> Update maven publication to include cksums.

- scripts/build.sh
Signed-off-by: Marc Handalian <handalm@amazon.com>
Add optional platform param sent by build workflow.  This param is optional in this script but will always be sent by the workflow.
> Update build.sh script to include optional platform param.

- .github/CODEOWNERS
Signed-off-by: Ryan Bogan <rbogan@amazon.com>
Add codeowners support for repo
Progress on:
[Meta issue](https://github.com/opensearch-project/project-meta/issues/31)
> Add codeowners support for repo

- .github/workflows/ci.yml
- build.gradle
Signed-off-by: Sarat Vemulapalli <vemulapallisarat@gmail.com>
Bumping common-utils to 1.2.2.0.
> Bumping common utils to 1.2.2.0

- .github/workflows/ci.yml
- .github/workflows/version.yml
Adds a workflow that increments the version in `build.gradle` whenever a new X.Y.Z.0 tag is pushed. 
- Successful run: https://github.com/dblock/common-utils/actions/runs/1631200088
- PR: https://github.com/dblock/common-utils/pull/1
The idea is that every repo can have its own version of this to increment a patch release. When, for example, 1.2.3 is released and tagged, every repo would automatically get a PR to increment the version to the next development iteration on the release branch (e.g. 1.2). These jobs would fail until a -SNAPSHOT build of OpenSearch is available, which is already automated. One would come to this PR, re-run the CI, and merge on green.
The version is removed from ci.yml because the workflow is not allowed to push a …
> Auto-increment version on new release tags.

- .github/workflows/ci.yml
- build.gradle
Increment version to `1.2.5` following the [Release] 1.2.5 issue
> increment version to 1.2.5

- build.gradle
Remove jcenter repository change that was missing during #115, see https://github.com/opensearch-project/opensearch-build/issues/1456 for additional context
> Remove jcenter repository missed on first pass

- .github/workflows/ci-17.yml
- .github/workflows/ci.yml
- DEVELOPER_GUIDE.md
- src/test/java/org/opensearch/commons/InjectSecurityTest.java
Signed-off-by: dblock <dblock@dblock.org>
- Uses the standard CI matrix to build and test on JDK 8, 11, and 14.
- Since Gradle 6 doesn't support JDK 17, build on 11, and test on 17. Not sure whether there's a better way to do this?
```
Run ./gradlew build --build-cache
./gradlew build --build-cache
shell: /usr/bin/bash -e {0}
env:
JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.14-101/x64
```
```
Run ./gradlew test --build-cache
./gradlew test --build-cache
shell: /usr/bin/bash -e {0}
env:
JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.2-8/x64
```
When we upgrade to Gradle 7 we can ran the 11, 14, 17 matrix and remove `ci.17.yml`.
Closes #100.
For …
> Run CI/CD on Java 8, 11, 14 and 17.

- build.gradle
- scripts/build.sh
Signed-off-by: dblock <dblock@dblock.org>
Add support for `-Dbuild.version_qualifier=alpha1`.
- Part of https://github.com/opensearch-project/opensearch-build/issues/1632.
> Add support for -Dbuild.version_qualifier.

- release-notes/opensearch-common-utils.release-notes-1.3.0.0.md
Backport to 1.x: Add release notes for version 1.3.0.0
[[Backport #132]](https://github.com/opensearch-project/common-utils/pull/132)
> Backport to 1.x: Add release notes for version 1.3.0.0

- release-notes/opensearch-common-utils.release-notes-1.3.0.0.md
Backport to 1.3 : Add release notes for version 1.3.0.0
Backport https://github.com/opensearch-project/common-utils/pull/132
> Backport to 1.3 : Add release notes for version 1.3.0.0

- src/main/java/org/opensearch/commons/destination/message/LegacyDestinationType.java
- src/main/kotlin/org/opensearch/commons/notifications/NotificationConstants.kt
- src/main/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/GetFeatureChannelListRequest.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/LegacyPublishNotificationRequest.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/NotificationsActions.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/EventSource.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/NotificationConfig.kt
- src/test/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/CreateNotificationConfigRequestTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/GetFeatureChannelListRequestTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/GetNotificationConfigResponseTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/GetNotificationEventResponseTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/LegacyPublishNotificationRequestTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/SendNotificationRequestTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/UpdateNotificationConfigRequestTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/EventSourceTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/NotificationConfigInfoTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/NotificationConfigSearchResultsTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/NotificationConfigTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/NotificationEventInfoTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/NotificationEventSearchResultTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/NotificationEventTests.kt
* Removes feature usage from NotificationConfig
* Removes feature usage from FeatureChannelList request
* Removes feature usage from EventSource
* Removes feature from LegacyPublishNotification
There will also be a complementary PR made in the Notifications project to integrate these changes.
There are still some indirect references to features like the enabled features returned in the GetPluginFeatures API which will be addressed in a follow-up PR.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#d …
> Remove feature and feature_list usage for Notifications

- build.gradle
Signed-off-by: Marc Handalian <handalm@amazon.com>
Updates common-utils to depend on the OpenSearch repositories plugin.  This allows common-utils to fetch snapshot lucene dependencies.
https://github.com/opensearch-project/OpenSearch/issues/2500
> Add opensearch repositories plugin to resolve lucene snapshot dependencies.

- src/main/kotlin/org/opensearch/commons/notifications/NotificationConstants.kt
- src/main/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/GetChannelListRequest.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/GetChannelListResponse.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/NotificationsActions.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/Channel.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/ChannelList.kt
- src/test/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/GetChannelListRequestTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/GetChannelListResponseTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/ChannelListTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/ChannelTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/FilterConfigListTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/FilterConfigTests.kt
Signed-off-by: Mohammad Qureshi <47198598+qreshi@users.noreply.github.com>
Renaming FeatureChannels, FeatureChannelList, etc. to remove "Feature" references to be more consistent with the API since it does not relate to features after recent changes.
> Rename references for Get Channels API for Notifications

- src/main/kotlin/org/opensearch/commons/notifications/NotificationConstants.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/GetPluginFeaturesResponse.kt
- src/test/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/action/GetPluginFeaturesResponseTests.kt
Signed-off-by: Mohammad Qureshi <47198598+qreshi@users.noreply.github.com>
Since `allowed_config_features` is no longer being used this PR removes it from the Notifications Get Plugin Features API response
> Remove allowedConfigFeatureList from GetPluginFeaturesResponse for Notifications

- build.gradle
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Change default opensearch version to 2.0.0-alpha1-SNAPSHOT
Part of https://github.com/opensearch-project/opensearch-build/issues/1632
> Change default opensearch version to 2.0.0-alpha1-SNAPSHOT

- scripts/build.sh
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Make CU hosts its own script before delete the one on build repo
We have 2 CU build script, one in build repo one in CU repo.
Our code base define that build repo script take priority over the CU repo script.
It would be better for CU to host their own build script in CU repo.
This is a pre-requisite to keep both script consistent before we remove the build script from build repo.
Example existing calls:
```
2022-03-31 22:32:38 INFO     Executing "bash /var/jenkins/workspace/distribution-build-opensearch/scripts/components/common-utils/build.sh -v 2.0.0 -q alpha1 -p linux -a arm64 -s false -o builds" in /tmp/tmpvo10muhh/common-utils
```
#131
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> Make CU hosts its own script before delete the one on build repo

- .github/workflows/ci.yml
In OpenSearch 2.0 we are building the complete distribution and every component with JDK 11, and testing and bundling JDK 17. Support for JDK 14, 15 and other non-LTS versions can be dropped. Remove building and testing with these JDKs from CI.
See https://opensearch.org/blog/technical-post/2022/03/opensearch-java-runtime/ for more information.
[[List any issues this PR will resolve]](https://github.com/opensearch-project/common-utils/issues/147)
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUT …
> Remove JDK 14

- src/main/java/org/opensearch/commons/destination/message/LegacyCustomWebhookMessage.java
- src/main/java/org/opensearch/commons/destination/message/LegacyDestinationType.java
- src/main/java/org/opensearch/commons/destination/message/LegacyEmailMessage.java
- src/main/kotlin/org/opensearch/commons/notifications/action/LegacyPublishNotificationRequest.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/NotificationEvent.kt
- src/test/java/org/opensearch/commons/destination/message/LegacyEmailMessageTest.java
The Notifications passthrough API is used for sending legacy messages for consumers of the old notification subproject in Alerting. Alerting has support for Email Destinations that need to use the passthrough API as a fallback mechanism for Destinations that have not migrated.
This PR adds support for email via passthrough.
> Support sending email message via Notifications passthrough API

- release-notes/opensearch-common-utils.release-notes-2.0.0.0-rc1.md
Add release notes for version 2.0.0.0-rc1
> Add release notes for version 2.0.0.0-rc1

- build.gradle
Signed-off-by: Aditya Jindal <aditjind@amazon.com>
This removes the RC1 qualifier from the common-utils plugin.
https://github.com/opensearch-project/common-utils/issues/165
> Removing RC1 as the qualifier from Common Utils

- .codecov.yml
- .github/workflows/ci.yml
> add code coverage badge

- build.gradle
Signed-off-by: Aditya Jindal <aditjind@amazon.com>
[[#165]](https://github.com/opensearch-project/common-utils/issues/165)
> [Backport 2.0] Removing RC1 as the qualifier from Common Utils (#168)

- src/main/kotlin/org/opensearch/commons/notifications/model/BaseModel.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/NotificationEvent.kt
Signed-off-by: Mohammad Qureshi <47198598+qreshi@users.noreply.github.com>
By default `ToXContent` has `isFragment` set to `true`. When calling `XContentHelper.toXContent()` for a fragment, it will wrap the contents in another object and expect a named object afterwards, this results in `IOException`s when not satisfied (like in NotificationEvent when converting to a string). 
Since all of the children of `BaseModel` are already wrapped in objects, they should not be treated as fragments. This PR updates BaseModel to be a `ToXContentObject` instead to reflect this.
For more information on following Developer Certificate of Origin and …
> Update Notifications BaseModel to extend ToXContentObject instead of ToXContent

- build.gradle
Replace https://github.com/opensearch-project/common-utils/pull/167, which had a DCO problem (fixed in https://github.com/opensearch-project/common-utils/pull/143). This was not done as part of post activity tasks when releasing 1.3.2.
> Incremented version to 1.3.3.

- build.gradle
Signed-off-by: Mohammad Qureshi <47198598+qreshi@users.noreply.github.com>
Updating `2.x` branch to `2.2` since `2.1` has already released. This is to match conventions of the proposed branching strategy for OpenSearch.
#202
> Bump 2.x branch to 2.2

- build.gradle
fix snakeyaml vulnerability issue by disabling detekt
#231 
#232 
#233 
#234 
#235 
> fix snakeyaml vulnerability issue by disabling detekt

- build.gradle
fix snakeyaml vulnerability issue by disabling detekt
> [Backport for PR #237] fix snakeyaml vulnerability issue by disabling detekt (#237)

- src/main/kotlin/org/opensearch/commons/alerting/AlertingPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/AlertingActions.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/DeleteMonitorRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/DeleteMonitorResponse.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertingPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/DeleteMonitorRequestTests.kt
expose delete monitor api from alerting
> expose delete monitor api from alerting

- src/main/kotlin/org/opensearch/commons/alerting/action/AlertingActions.kt
Signed-off-by: Petar Dzepina <petar.dzepina@vroom.com>
added @JvmField annotation to prevent generating getters
> @JvmField annotation to Action constants

- build.gradle
disable detekt so that snakeyaml <= 1.31 is not used
#257 
> disable detekt so that snakeyaml <= 1.31 is not used

- src/main/java/org/opensearch/commons/destination/message/LegacyDestinationType.java
- src/main/java/org/opensearch/commons/destination/message/LegacySNSMessage.java
- src/main/java/org/opensearch/commons/destination/util/Util.java
- src/main/kotlin/org/opensearch/commons/notifications/action/LegacyPublishNotificationRequest.kt
- src/test/java/org/opensearch/commons/destination/message/LegacySNSMessageTest.java
- src/test/java/org/opensearch/commons/destination/util/UtilTest.java
Signed-off-by: AWSHurneyt <hurneyt@amazon.com>
Added legacy support for SNS messages. These changes will need to be back ported back to version 2.3.
> Added legacy support for SNS messages.

- src/main/kotlin/org/opensearch/commons/alerting/action/GetAlertsRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/GetFindingsRequest.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetAlertsRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetFindingsRequestTests.kt
Relates to : 
[[FEATURE] Support fetching bulk alerts for multiple monitors in get alerts API #587](https://github.com/opensearch-project/alerting/issues/587)
[[FEATURE]Support fetching bulk findings for multiple monitors in get findings API #588](https://github.com/opensearch-project/alerting/issues/588)
> Accept of list of monitor ids in findings and alerts request dtos

- src/main/kotlin/org/opensearch/commons/alerting/action/GetAlertsRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/GetFindingsRequest.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetAlertsRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetFindingsRequestTests.kt
Backports https://github.com/opensearch-project/common-utils/pull/277 to 2.x
> [Backport 2.x] Accept of list of monitor ids in findings and alerts request dtos (#277)

- src/main/java/org/opensearch/commons/authuser/User.java
- src/main/java/org/opensearch/commons/destination/message/LegacyBaseMessage.java
- src/main/java/org/opensearch/commons/destination/message/LegacyCustomWebhookMessage.java
- src/main/java/org/opensearch/commons/rest/SecureRestClientBuilder.java
- src/main/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInput.kt
- src/test/java/org/opensearch/commons/destination/message/LegacyCustomWebhookMessageTest.java
- src/test/java/org/opensearch/commons/rest/IntegrationTests.java
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInputTests.kt
this PR fixes the build failures in `common-utils` due to `upgrade of Apache HttpClient / Core to 5.x` in `opensearch-core`.
https://github.com/opensearch-project/OpenSearch/commit/4833e080cc506237fee5aa90767d6f49d952bec3
#279
> Migrate to Apache HttpClient / Core 5.x

- src/main/kotlin/org/opensearch/commons/alerting/action/GetAlertsRequest.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetAlertsRequestTests.kt
Related to [[FEATURE] Fetching or acknowledging alert by passing alert id without monitor Id #602](https://github.com/opensearch-project/alerting/issues/602)
> add list of alert ids in get alerts request

- src/main/kotlin/org/opensearch/commons/alerting/model/DataSources.kt
Signed-off-by: Petar <petar.dzepina@gmail.com>
Added history index params to DataSources model
> added params to Datasources

- src/main/kotlin/org/opensearch/commons/alerting/action/GetFindingsResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/FindingDocument.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/FindingWithDocs.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetFindingsResponseTests.kt
fix findings parsing logic introduced by pr #292
> fix findings parsing logic introduced by pr #292

- src/main/java/org/opensearch/commons/rest/SecureRestClientBuilder.java
Signed-off-by: Ashish Agrawal <ashisagr@amazon.com>
- Force version policy on secure client to fix invalid protocal version
N/A
> Force version policy on secure client to fix invalid protocal version

- src/main/kotlin/org/opensearch/commons/alerting/action/IndexMonitorRequest.kt
Signed-off-by: Ashish Agrawal <ashisagr@amazon.com>
Support backend roles in indexMonitorRequest
N/A
> Support backend roles in indexMonitorRequest

- release-notes/opensearch-common-utils.release-notes-2.4.0.0.md
> 2.4 release notes

- src/main/java/org/opensearch/commons/rest/SecureRestClientBuilder.java
Signed-off-by: bowenlan-amzn <bowenlan23@gmail.com>
Duplicate the super admin client constructor with hosts params. Currently we hardcode the host to be localhost:9200 in super admin client.
https://github.com/opensearch-project/index-management/issues/612
> Add a super admin client builder w/ hosts params

- src/main/java/org/opensearch/commons/rest/SecureRestClientBuilder.java
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
When using JDK 16+, the `org.apache.hc.core5.http.ParseException: Invalid protocol version` is being thrown.
See please https://issues.apache.org/jira/browse/HTTPCLIENT-2219
> Addressing 'org.apache.hc.core5.http.ParseException: Invalid protocol version' under JDK 16+

- src/main/java/org/opensearch/commons/ConfigConstants.java
- src/main/java/org/opensearch/commons/rest/SecureRestClientBuilder.java
- src/test/java/org/opensearch/commons/ConfigConstantsTest.java
- src/test/java/org/opensearch/commons/rest/IntegrationTests.java
Update configuration use of keystore passwords to utilize secure variants when present, falling back to the insecure variants for legacy reasons
Related to changes introduced to security plugin in PR:
* https://github.com/opensearch-project/security/pull/2296 
#334
> Update keystore password to utilize secure variants

- .github/workflows/maven-publish.yml
- build.gradle
Publish snapshots to maven via GHA.
Cherry-picked the changes in the `main` branch PR https://github.com/opensearch-project/common-utils/pull/362
https://github.com/opensearch-project/common-utils/issues/361
Tested locally on my `2.x`-based branch.
```
$ find snapshots | sort   
snapshots
snapshots/org
snapshots/org/opensearch
snapshots/org/opensearch/common-utils
snapshots/org/opensearch/common-utils/2.6.0.0-SNAPSHOT
snapshots/org/opensearch/common-utils/2.6.0.0-SNAPSHOT/common-utils-2.6.0.0-20230222.015350-1-javadoc.jar
snapshots/org/opensearch/common-utils/2.6.0.0-SNAPSHOT/common-utils-2.6.0.0-20230222.015350-1-javadoc.jar.md5
snapshots/org/opensearch/common-utils/2.6.0.0-SNAPSHOT/common-utils-2.6.0.0-20230222.015350-1-javadoc.jar.sha1 …
```
> 2.x branch - Publish snapshots to maven via GHA

- .github/workflows/auto-release.yml
Add auto Github release workflow to automatically publish a release when a tag is pushed.
https://github.com/opensearch-project/common-utils/issues/356
> Add auto Github release workflow

- src/main/kotlin/org/opensearch/commons/notifications/model/Sns.kt
- src/test/kotlin/org/opensearch/commons/notifications/model/SnsTests.kt
Fixed SNS regex for validation on notification channel to support SNS FIFO topics.
SNS FIFO topic ARN regex validation was throwing error
`java.lang.IllegalArgumentException: Invalid AWS SNS topic ARN: arn:aws:sns:ap-southeast-2:33365477133:sns-fifo-alerting.fifo`
#382 
> Fix SNS regex for validation on notification channel to support SNS FIFO topics.

- src/main/kotlin/org/opensearch/commons/alerting/AlertingPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/AlertingActions.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/ChainedFindings.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/ChainedMonitorFindings.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/CompositeInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Delegate.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Finding.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Sequence.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Workflow.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/WorkflowInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/util/IndexUtils.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertingPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/CompositeInputTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
> Added workflow as a composite monitor

- src/main/kotlin/org/opensearch/commons/alerting/model/Delegate.kt
> Renamed chained monitor findings

- src/main/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/ChainedMonitorFindings.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/CompositeInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Delegate.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Sequence.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Workflow.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/WorkflowInput.kt
> Imports fixed

- src/main/java/org/opensearch/commons/InjectSecurity.java
- src/test/java/org/opensearch/commons/InjectSecurityTest.java
Added user_info injection of User object in InjectSecurity
Pre-requisite for https://github.com/opensearch-project/alerting/pull/852
> InjectSecurity - inject User object in UserInfo in threadContext

- src/main/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequest.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertingPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
Added validation when indexing the workflow
> Added validation on IndexWorkflowRequest class

- release-notes/opensearch-common-utils.release-notes-2.7.0.0.md
Added 2.7 release notes.
https://github.com/opensearch-project/common-utils/issues/395
> Added 2.7 release notes.

- .github/CODEOWNERS
- src/main/kotlin/org/opensearch/commons/alerting/AlertingPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/AlertingActions.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/PublishFindingsRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/SubscribeFindingsResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Finding.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetFindingsResponseTests.kt
integrate security-analytics & alerting for correlation engine
> integrate security-analytics & alerting for correlation engine

- src/main/kotlin/org/opensearch/commons/alerting/model/Alert.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/NoOpTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Trigger.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
Added NoOpTrigger to be used when constructing monitor error alerts or alerts which are not generated as a result of ran triggers
> NoOpTrigger

- .github/workflows/maven-publish.yml
Switches format of branches to run publish maven on to list. In https://github.com/opensearch-project/common-utils/actions/workflows/maven-publish.yml, all workflows are being triggered manually instead of push. This will allow workflow to be triggered on push to respective branches.
See k-NN: 
1. https://github.com/opensearch-project/k-NN/blob/main/.github/workflows/maven-publish.yml
2. https://github.com/opensearch-project/k-NN/actions/workflows/maven-publish.yml
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of …
> Switch publish maven branches to list

- src/main/kotlin/org/opensearch/commons/alerting/model/Alert.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/ChainedAlertTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Trigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Workflow.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertingPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetFindingsResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowResponseTests.kt
adds models for chained alert trigger and chained alerts. 
adds triggers to workflows. only chained alerts triggers are allowed
Chained alerts will be consumed in Workflows
> adds models for chained alert trigger and chained alerts

- .github/CODEOWNERS
- MAINTAINERS.md
Sync up MAINTAINERS to CODEOWNERS.
Closes https://github.com/opensearch-project/common-utils/issues/357.
> Sync up MAINTAINERS to CODEOWNERS.

- src/main/kotlin/org/opensearch/commons/alerting/model/Alert.kt
accept workflow argument in chained alert constructor. Workflow would contain id, name and user fields which make it a good dto to pass along similar to how other types of alerts accept monitor object in constructor
> accept workflow argument in chained alert constructor

- src/main/kotlin/org/opensearch/commons/alerting/AlertingPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/AlertingActions.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/ChainedMonitorFindings.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/CompositeInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Delegate.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Finding.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Sequence.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Workflow.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/WorkflowInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/util/IndexUtils.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertingPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/CompositeInputTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
**PRs merged into feature branch `feature/composite-monitors`:**
Added Alerting workflow model (https://github.com/opensearch-project/common-utils/pull/380)
Renamed chained monitor findings (https://github.com/opensearch-project/common-utils/pull/390)
Imports fixed (https://github.com/opensearch-project/common-utils/pull/394)
Added validation on IndexWorkflowRequest class (https://github.com/opensearch-project/common-utils/pull/405)
Extended deleted workflow response with list of monitor ids failed to delete (#416)
> Adds workflows model and workflow actions for Alerting Plugin

- src/main/kotlin/org/opensearch/commons/alerting/AlertingPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/AlertingActions.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/ChainedMonitorFindings.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/CompositeInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Delegate.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Finding.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Sequence.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Workflow.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/WorkflowInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/util/IndexUtils.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertingPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/DeleteWorkflowResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetWorkflowRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetWorkflowResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/CompositeInputTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/WriteableTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
PRs merged into feature branch feature/composite-monitors:
Added Alerting workflow model (https://github.com/opensearch-project/common-utils/pull/380)
Renamed chained monitor findings (https://github.com/opensearch-project/common-utils/pull/390)
Imports fixed (https://github.com/opensearch-project/common-utils/pull/394)
Added validation on IndexWorkflowRequest class (https://github.com/opensearch-project/common-utils/pull/405)
Extended deleted workflow response with list of monitor ids failed to delete (https://github.com/opensearch-project/common-utils/pull/416)
> Adds workflows model and workflow actions for Alerting Plugin 

- .github/workflows/maven-publish.yml
Modify triggers to push snapshots on all branches. See history here: https://github.com/opensearch-project/common-utils/actions/workflows/maven-publish.yml
We had to manually trigger the workflow many times. 
> Modify triggers to push snapshots on all branches

- src/main/kotlin/org/opensearch/commons/alerting/model/Alert.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/ChainedAlertTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Trigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Workflow.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertingPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetAlertsResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetFindingsResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/WriteableTests.kt
**Merging into main the following feature branch commits/merged PRs:**
accept workflow argument in chained alert constructor #435
Adds workflows model and workflow actions for Alerting Plugin #436
adds models for chained alert trigger and chained alerts #426
> Adds Chained alerts triggers for workflows

- src/main/kotlin/org/opensearch/commons/alerting/model/Alert.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/AcknowledgeAlertResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetAlertsResponseTests.kt
Add workflowId field in alert model.
This field would be populated when alerts are created by monitors executing within a workflow. Else field would be an empty string
> Add workflowId field in alert model

- src/main/kotlin/org/opensearch/commons/alerting/AlertingPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/AlertingActions.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowAlertsRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowAlertsResponse.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Alert.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertingPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/AcknowledgeAlertResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/AcknowledgeChainedAlertRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetAlertsResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetWorkflowAlertsRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetWorkflowAlertsResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/PublishFindingsRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
cherrypicked commit from  #472 to 2.x 
backport CI had failed due to conflicts to be resolved
> [Backport 2.x] apis for get workflow alerts and acknowledge chained alerts (#472)

- src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowAlertsRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Alert.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Workflow.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetWorkflowAlertsRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetWorkflowResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
- auditDelegateMonitorAlerts flag gives the option to create alerts in Audit state for delegate monitors in workflows.
- this flag is set to true by default in alerting. it will be set to false in security analytics
-
> add auditDelegateMonitorAlerts flag

- src/main/kotlin/org/opensearch/commons/alerting/action/GetWorkflowAlertsRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Alert.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Workflow.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetWorkflowAlertsRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetWorkflowResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
* add auditDelegateMonitorAlerts flag
* add audit state check in error alert validation
* add test to verify workflow with auditDelegateMonitor flag null
---------
> Backport 2.x -  add auditDelegateMonitorAlerts flag (#476)

- src/main/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInput.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
Implemented support for configuring a cluster metrics monitor to call cat/indices, and cat/shards.
Documentation issue https://github.com/opensearch-project/documentation-website/issues/4437
https://github.com/opensearch-project/alerting/issues/611
> Implemented support for configuring a cluster metrics monitor to call cat/indices, and cat/shards.

- src/main/kotlin/org/opensearch/commons/alerting/AlertingPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/notifications/action/BaseResponse.kt
- src/main/kotlin/org/opensearch/commons/notifications/model/NotificationEvent.kt
- src/main/kotlin/org/opensearch/commons/utils/SecureClientWrapper.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertingPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterfaceTests.kt
make common-utils core compatible after core #9082
> make common-utils core compatible after core #9082

- src/main/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/ChainedMonitorFindings.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/CompositeInputTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
Adds support for passing a list monitor ids in chained monitor findings. This helps filter data of a monitor in workflow based on findings of multiple monitors instead of a single monitor.
If workflow sequence looks like: 
[m1] -> [m2] -> [m3 (chained findings of m1, m2)]
this means m3's data input would be the related doc ids from findings of m1 and m2.
for backward compatibility reasons, the monitorId field would be given preference over the new list type field, monitorIds, if both are provided.
> support list of monitor ids in Chained Monitor Findings

- src/main/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/ChainedMonitorFindings.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexWorkflowRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/CompositeInputTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
support list of monitor ids in Chained Monitor Findings
Creating manual backport PR as backport CI failed due to conflicts
> (Backport 2.x) support list of monitor ids in Chained Monitor Findings (#514)

- src/main/kotlin/org/opensearch/commons/alerting/alerts/AlertError.kt
- src/test/kotlin/org/opensearch/commons/alerting/alerts/AlertErrorTests.kt
Currently alertError class' message field is storing exception messages along with IP addresses if message contains any IPs
This change obfuscates the ip address in exception messages stored in disk and shown to user
> obfuscate ip addresses in alert error message

- release-notes/opensearch-common-utils.release-notes-2.10.0.0.md
> Adds 2.10.0.0 release notes

- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelQuery.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetFindingsResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/WriteableTests.kt
Query string query supports fields parameter in percolate queries.
https://opensearch.org/docs/latest/query-dsl/full-text/query-string/#parameters 
to support queries with multiple fields or wildcards in percolate query.
This enabled queries like
```
GET /_search
{
"query": {
"query_string": {
"fields": [ "name", "description" ],
"query": "apple AND tree"
}
}
}
```
[[BUG] Unable to create doc level monitor when passing wildcard field names in query string query ](https://github.com/opensearch-project/alerting/issues/1229)
> add 'fields' parameter in doc level query object.

- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelQuery.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
add fields param in toxcontent() for doc level query
> add fields param in toxcontent() for doc level query

- src/main/java/org/opensearch/commons/ConfigConstants.java
- src/main/java/org/opensearch/commons/authuser/User.java
- src/test/java/org/opensearch/commons/authuser/UserTest.java
Adds a static helper method on the User class to determine if the user is in the security plugin's `plugins.security.authcz.admin_dn` list.
https://github.com/opensearch-project/security/issues/3413
> Add User.isAdminDn to User class

- .github/workflows/ci.yml
Add Java 11/17/21 matrix for build, test and integration checks
Part of https://github.com/opensearch-project/OpenSearch/issues/10334
> Add Java 11/17/21 matrix for build, test and integration checks

- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelQuery.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetFindingsResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/WriteableTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
Revert commits dcf288d and d92419d related to adding fields param in DocLevelQuery object.
> Revert commits dcf288d and d92419d

- src/main/kotlin/org/opensearch/commons/alerting/model/BucketLevelTrigger.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/BucketLevelTriggerTests.kt
Adds the condition to the BucketLevelTrigger templateArg so that it can be consumed in notifications
ctx.trigger before this change:
```
{
id=0tgobIwBxdVVQaI5AhDn,
name=mytrigger,
severity=1,
actions=[
{
name=myaction
}
],
parentBucketPath=versions
}
```
ctx.trigger after this change:
```
{
id=0tgobIwBxdVVQaI5AhDn,
name=mytrigger,
severity=1,
actions=[
{
name=myaction
}
],
parentBucketPath=versions,
condition=params.cpu_avg > 0
}
```
https://github.com/opensearch-project/alerting/issues/1299
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING. …
> Add condition to the templateArg of BucketLevelTrigger

- src/main/java/org/opensearch/commons/rest/SecureRestClientBuilder.java
- src/test/java/org/opensearch/commons/rest/IntegrationTests.java
These changes stop common-utils from using 'admin' as a password in any security plugin related workflows
https://github.com/opensearch-project/common-utils/issues/579
- [N] New functionality includes testing.
- [Y] All tests pass
- [N] New functionality has been documented.
- [N/A] New functionality has javadoc added
- [Y] Commits are signed per the DCO using --signoff 
> changed all usages of 'admin' as a password to something different

- src/main/kotlin/org/opensearch/commons/alerting/model/Alert.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInput.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
Added `clusters` field to support cross-cluster cluster metrics monitors.
Documentation PR for reference https://github.com/opensearch-project/documentation-website/pull/6350
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/796
> Implemented cross-cluster monitor support

- src/main/kotlin/org/opensearch/commons/alerting/model/Alert.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInput.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInputTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
> [Backport 2.x] Implemented cross-cluster monitor support #584

- release-notes/opensearch-common-utils.release-notes-2.12.0.0.md
Add release notes for 2.12 for common-utils
> Added release notes for 2.12.0

- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelQuery.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/WriteableTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
add queryFieldNames field in Doc Level Queries. When specified this field gives the list of fields to query and fetch from all docs to be searched in the index as opposed to fetching entire `_source` of each document.
> add queryFieldNames field in Doc Level Queries

- build.gradle
Forced ktlint to use logback-core:1.2.13, and logback-classic:1.2.13 to address CVE.
> Forced ktlint to use logback-core:1.2.13, and logback-classic:1.2.13 to address CVE.

- src/main/kotlin/org/opensearch/commons/alerting/action/GetFindingsRequest.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetFindingsRequestTests.kt
Findings API Enhancements
[[Issue](https://github.com/opensearch-project/security-analytics/issues/795)
Alerting PR: https://github.com/opensearch-project/alerting/pull/1427/files
SA PR: https://github.com/opensearch-project/security-analytics/pull/803/files
> Feature findings enhancemnt

- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelQuery.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/WriteableTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
* add queryFieldNames field in Doc Level Queries
* add tests to verify queryFieldNames field in DocLevelQuery
---------
(cherry picked from commit 75925dcdbc98e29c07e007676ea6c68ee7468dec)
> [Backport 2.9] add queryFieldNames field in Doc Level Queries (#582) (#597)

- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelQuery.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/WriteableTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
Manual backport to 2.7 
- #582 
> [Backport 2.7] add queryFieldNames field in Doc Level Queries (#582)

- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelQuery.kt
- src/main/kotlin/org/opensearch/commons/utils/ValidationHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/DocLevelMonitorInputTests.kt
Changes the doc level query name validation to restrict the name from 0-256 characters, similar to the validation done on the front end
Name validation regex modified from https://github.com/opensearch-project/alerting/blob/d2a590e744c920820536efc5e1a88a4185eeed74/alerting/src/main/kotlin/org/opensearch/alerting/util/IndexUtils.kt#L29
> Change doc level query name validation

- src/main/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInput.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/ClusterMetricsInputTests.kt
Wrapped URI syntax exception in IllegalArgument exception.
> Wrapped URI syntax exception in IllegalArgument exception.

- src/main/kotlin/org/opensearch/commons/alerting/action/GetAlertsRequest.kt
changes to add start_time and end_time filters to getAlertsRequest
> changes to add start_time and end_time filters to getAlertsRequest

- src/main/kotlin/org/opensearch/commons/alerting/model/BaseAlert.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/CorrelationAlert.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/UnifiedAlert.kt
- src/test/kotlin/org/opensearch/commons/alerting/CorrelationAlertTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/utils/TestHelpers.kt
* Creates a model class for GenericAlert i.e BaseAlert class which can be extended later on by monitor based alerts
* Creates a model class for CorrelationAlert which extends BaseAlert class
* Tests added to support CorrelationAlerts
[Alerts in Correlations](https://github.com/opensearch-project/security-analytics/issues/988)
> CorrelationAlert model added

- src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
- src/main/kotlin/org/opensearch/commons/alerting/util/IndexUtils.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/GetMonitorResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexMonitorResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
changes to add support for remote monitors in alerting
[#1546](https://github.com/opensearch-project/alerting/issues/1546)
> changes to add support for remote monitors in alerting

- src/main/kotlin/org/opensearch/commons/alerting/model/Input.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Trigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/remote/monitors/RemoteMonitorInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/remote/monitors/RemoteMonitorTrigger.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/DocLevelMonitorFanOutRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/DocLevelMonitorFanOutResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/WriteableTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
changes to support generic inputs and triggers in remote monitors
[#1546](https://github.com/opensearch-project/alerting/issues/1546)
> changes to support generic inputs and triggers in remote monitors

- src/main/kotlin/org/opensearch/commons/alerting/model/remote/monitors/RemoteDocLevelMonitorInput.kt
fix serde of RemoteDocLevelMonitorInput
#1546
> fix serde of RemoteDocLevelMonitorInput

- src/main/kotlin/org/opensearch/commons/alerting/model/DataSources.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/DataSourcesTests.kt
Fixing a breaking change to Security Analytics Plugin caused by https://github.com/opensearch-project/common-utils/pull/663
> adding ctor with optional comments indices args

- src/main/kotlin/org/opensearch/commons/alerting/model/DataSources.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
Fix for breaking change in Security Analytics plugin
- [N/A] New functionality has been documented.
- [N/A] New functionality has javadoc added
> Fixing DataSources Parsing Errors

- src/main/kotlin/org/opensearch/commons/alerting/model/DataSources.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
* attempt to fix DataSources breaking change
Signed-off-by: Dennis Toepker <toepkerd@amazon.com>
* adding default comments index values instead of passing null into constructor
Signed-off-by: Dennis Toepker <toepkerd@amazon.com>
---------
Signed-off-by: Dennis Toepker <toepkerd@amazon.com>
Co-authored-by: Dennis Toepker <toepkerd@amazon.com>
(cherry picked from commit f4b2e1b9de2b660b66815610b214ffd1f4ec579c)
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#devel …
> [Backport 2.x] Fixing DataSources Parsing Errors (#678)

- release-notes/opensearch-common-utils.release-notes-2.15.0.0.md
- src/main/kotlin/org/opensearch/commons/alerting/action/IndexCommentRequest.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Comment.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexCommentRequestTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/action/IndexCommentResponseTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/WriteableTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/XContentTests.kt
* adding entityType to Comment model
* updated tests
* removing EntityType enum class, entity type in documents will just be strings
* fixed unit tests
* adding tests and release notes
* moved comment test to WriteableTests
* updated writeable test
---------
Manual backport to 2.x of PR #671 
> [Backport 2.x] Adding EntityType to Comment Model (#671)

- src/main/kotlin/org/opensearch/commons/alerting/model/BucketLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelMonitorInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/DocumentLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Input.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/QueryLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Schedule.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/SearchInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/action/Action.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/remote/monitors/RemoteDocLevelMonitorInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/remote/monitors/RemoteMonitorInput.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/BucketLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/DocumentLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/MonitorsTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/QueryLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/ScheduleTest.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/SearchInputTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/action/ActionTests.kt
Backport https://github.com/opensearch-project/common-utils/pull/710 to 2.15
Ran security analytics and alerting tests locally with these changes.
> [Backport 2.15] add missing ctx variables (#710)

- src/main/kotlin/org/opensearch/commons/alerting/model/BucketLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelMonitorInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/DocumentLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Input.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/QueryLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Schedule.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/SearchInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/action/Action.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/BucketLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/DocumentLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/MonitorsTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/QueryLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/ScheduleTest.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/SearchInputTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/action/ActionTests.kt
Backport https://github.com/opensearch-project/common-utils/pull/710 to 2.13
Ran security analytics and alerting tests locally with these changes.
> [Backport 2.13] add missing ctx variables (#710)

- src/main/kotlin/org/opensearch/commons/alerting/model/BucketLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelMonitorInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/DocumentLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Input.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/QueryLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Schedule.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/SearchInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/action/Action.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/BucketLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/DocumentLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/MonitorsTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/QueryLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/ScheduleTest.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/SearchInputTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/action/ActionTests.kt
Backport #710 to 2.11
Ran security analytics and alerting tests locally with these changes. 
> [Backport 2.11] add missing ctx variables (#710)

- src/main/kotlin/org/opensearch/commons/alerting/model/BucketLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelMonitorInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/DocumentLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Input.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/QueryLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Schedule.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/SearchInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/action/Action.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/BucketLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/DocumentLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/MonitorsTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/QueryLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/ScheduleTest.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/SearchInputTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/action/ActionTests.kt
Backport #710 to 2.9
Ran security analytics and alerting tests locally with these changes. 
> [Backport 2.9] add missing ctx variables (#710)

- src/main/kotlin/org/opensearch/commons/alerting/model/BucketLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelMonitorInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/DocumentLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Input.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/QueryLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Schedule.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/SearchInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/action/Action.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/BucketLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/DocumentLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/MonitorsTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/QueryLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/ScheduleTest.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/SearchInputTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/action/ActionTests.kt
Backport #710 to 2.9
Ran security analytics and alerting tests locally with these changes.
> [Backport 2.7] add missing ctx variables (#710)

- src/main/kotlin/org/opensearch/commons/alerting/model/BucketLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelMonitorInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/DocumentLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Input.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/QueryLevelTrigger.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Schedule.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/SearchInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/action/Action.kt
- src/test/kotlin/org/opensearch/commons/alerting/TestHelpers.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/BucketLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/DocumentLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/MonitorsTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/QueryLevelTriggerTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/ScheduleTest.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/SearchInputTests.kt
- src/test/kotlin/org/opensearch/commons/alerting/model/action/ActionTests.kt
Backport https://github.com/opensearch-project/common-utils/pull/710 to 2.5
Ran security analytics and alerting tests locally with these changes.
> [Backport 2.5] add missing ctx variables (#710)

- src/main/kotlin/org/opensearch/commons/alerting/action/AlertingActions.kt
Modifying the alerting comments permissions to not be put under `alerting/alerts`. With the way `alerting_ack_alerts` is currently configured in Security plugin, putting comments permissions under `alerting/alerts` would give someone with `alerting_ack_alerts` role full access to alerting comments (including edit and delete)
> changing the names of the alerting comment actions

- src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
changes to support dynamic deletion of doc-level monitor query indices. added flag `deleteQueryIndexInEveryRun`
> changes to support dynamic deletion of doc-level monitor query indices added flag deleteQueryIndexInEveryRun

- .github/workflows/ci.yml
- DEVELOPER_GUIDE.md
- build.gradle
Set common-utils 3.0.0 baseline JDK version to JDK-21
Closes https://github.com/opensearch-project/common-utils/issues/668
> Set common-utils 3.0.0 baseline JDK version to JDK-21

- src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
changes to support dynamic deletion of doc-level monitor query indices. manual backport #734 
> changes to support dynamic deletion of doc-level monitor query indices

- src/main/kotlin/org/opensearch/commons/alerting/model/DocLevelMonitorInput.kt
- src/main/kotlin/org/opensearch/commons/alerting/model/Monitor.kt
Detectors configured with aggregation sigma rules should ideally generate only one alert in one execution when a set of documents match the rule’s condition. But currently there are duplicate alerts being generated when aggregate sigma rules are matched.
This PR adds a field in monitor  `fanoutEnabled` (optional field), default value of this flag will be true. When detector is created/updated, the value of this field will be set to false in case chained findings doc level monitor, this will ensure that fanout approach will be disabled when executing doc level monitor
For more information on following Developer …
> Monitor model changed to add an optional fanoutEnabled field

- src/main/kotlin/org/opensearch/commons/alerting/aggregation/bucketselectorext/BucketSelectorIndices.kt
- src/test/kotlin/org/opensearch/commons/alerting/bucketselectorext/BucketSelectorExtAggregatorTests.kt
1. Fix bucket selector aggregation writeable name.
This PR will have a follow-up PR in the alerting plugin to fix the way we register the aggregation.
This change is needed back to v1.1; however, these assets were only moved to the common utils repo from alerting in v2.4. Will raise separate PRs to backport these changes further.
> Fix bucket selector aggregation writeable name.

- .github/workflows/ci.yml
1. Includes PR https://github.com/opensearch-project/common-utils/pull/774/
2. Similar to PR https://github.com/opensearch-project/anomaly-detection/pull/1373/files, adjusted the workflow configuration to successfully checkout the branch with actions/checkout@v4
> Fix 2.x branch github CI workflow.

- src/main/kotlin/org/opensearch/commons/alerting/AlertingPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/utils/SecureClientWrapper.kt
- src/test/kotlin/org/opensearch/commons/alerting/AlertingPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/notifications/NotificationsPluginInterfaceTests.kt
Fix imports related to split package of org.opensearch.transport
Related to https://github.com/opensearch-project/OpenSearch/pull/17272
> Fix imports related to split package of org.opensearch.transport

- src/main/kotlin/org/opensearch/commons/replication/ReplicationPluginInterface.kt
- src/main/kotlin/org/opensearch/commons/replication/action/ReplicationActions.kt
- src/main/kotlin/org/opensearch/commons/replication/action/StopIndexReplicationRequest.kt
- src/test/kotlin/org/opensearch/commons/replication/ReplicationPluginInterfaceTests.kt
- src/test/kotlin/org/opensearch/commons/replication/action/StopIndexReplicationRequestTests.kt
Backporting this [PR](https://github.com/opensearch-project/common-utils/pull/667) on 2.x branch. 
Pls see the PR on main branch for complete background.
In short, this moves ccr-related action and request classes to common-utils, so that multiple plugins  (ccr, ism) can make use of the same.
[Stop replication feature in ISM](https://github.com/opensearch-project/index-management/issues/726)
> [2.x] Adding replication (CCR) plugin interface and classes

- src/main/kotlin/org/opensearch/commons/replication/ReplicationPluginInterface.kt
- src/test/kotlin/org/opensearch/commons/replication/ReplicationPluginInterfaceTests.kt
As per the review comment received on [PR](https://github.com/opensearch-project/common-utils/pull/667#discussion_r1966444486) on main branch, the suggestion was to convert ReplicationPluginInterface to an object and have static methods, instead of an open class and open methods.
The change works and is validated.
On 2.x branch, the [PR](https://github.com/opensearch-project/common-utils/pull/789) was already merged with open class, this new PR is to only fix this gap on the 2.x branch.
[Unfollow action](https://github.com/opensearch-project/index-management/issues/726)
For more information on following Developer Certificate of Origin and signing off your commits, please …
> [2.x] Updating ReplicationPluginInterface from open class to object

- release-notes/opensearch-common-utils.release-notes-3.0.0.0-alpha1.md
Add 3.0.0.0-alpha1 release notes in common utils
https://github.com/opensearch-project/common-utils/issues/498
- ~~[ ] New functionality includes testing.~~
- ~~[ ] New functionality has been documented.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~~
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/common-utils/blob/main/CONTRIBUTING.md#dev …
> Add 3.0.0.0-alpha1 release notes in common utils

- src/main/java/org/opensearch/commons/InjectSecurity.java
- src/main/java/org/opensearch/commons/authuser/User.java
- src/main/java/org/opensearch/commons/authuser/Utils.java
- src/test/java/org/opensearch/commons/InjectSecurityTest.java
- src/test/java/org/opensearch/commons/authuser/UserTest.java
- src/test/java/org/opensearch/commons/authuser/UtilsTest.java
Escape pipe while setting UserInfo in ThreadContext, Unescape pipe while reading UserInfo from ThreadContext
https://github.com/opensearch-project/security/issues/2756
- [] New functionality includes testing.
- [NA] New functionality has been documented.
- [NA] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [NA] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).
For more information on following Developer Certificate of Origin and signing off your commits, please check …
> Escape/Unescape pipe UserInfo in ThreadContext

- build.gradle
Change 3.0.0 qualifier from alpha1 to beta1
The core repo has already been changed to beta1: https://github.com/opensearch-project/OpenSearch/pull/17621
> Change 3.0.0 qualifier from alpha1 to beta1

- .github/workflows/maven-publish.yml
- build.gradle
Update the Maven Snapshots publish URL in accordance with the recent Sonatype migration. 
https://central.sonatype.org/publish/publish-portal-snapshots/
We have stored the `onepassword` token in this repo secrets and new credentials for Sonatypes username & password have been stored in `onepassword`.  These credentials will be exported as env variables which used by maven publish.
Part of a campaign from https://github.com/opensearch-project/opensearch-build/issues/5551
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/common-utils/blob/main/CONTRIBUTING.md#developer-certifi …
> Update Maven snapshots publishing endpoint and credential retrieval

- src/main/java/org/opensearch/commons/authuser/User.java
- src/test/java/org/opensearch/commons/authuser/UserTest.java
Companion security PR: https://github.com/opensearch-project/security/pull/5519
This PR adds additional information about the requested tenant and the level of access the authenticated user has to that tenant. i.e. one of No Access, Write access or Read access.
Resolves https://github.com/opensearch-project/reporting/issues/1099
> Add tenancy access info to serialized user in threadcontext
